# Generated by Django 4.1.1 on 2022-09-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='contact',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
