# Generated by Django 4.1.1 on 2022-09-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_emp_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
